// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(ScrumBoardContext))]
    partial class ScrumBoardContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApplicationCore.Entities.ScrumBoardAggregate.Board", b =>
                {
                    b.Property<int>("BoardUnicalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BoardName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("BoardUnicalID");

                    b.ToTable("Board", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.ScrumBoardAggregate.Column", b =>
                {
                    b.Property<int>("ColumnUnicalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BoardID")
                        .HasColumnType("int");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("ColumnUnicalID");

                    b.HasIndex("BoardID");

                    b.ToTable("Column", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.ScrumBoardAggregate.Task", b =>
                {
                    b.Property<int>("TaskUnicalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ColumnID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("TaskPriority")
                        .HasColumnType("int");

                    b.HasKey("TaskUnicalId");

                    b.HasIndex("ColumnID");

                    b.ToTable("Task", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.ScrumBoardAggregate.Column", b =>
                {
                    b.HasOne("ApplicationCore.Entities.ScrumBoardAggregate.Board", "Board")
                        .WithMany("Columns")
                        .HasForeignKey("BoardID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("ApplicationCore.Entities.ScrumBoardAggregate.Task", b =>
                {
                    b.HasOne("ApplicationCore.Entities.ScrumBoardAggregate.Column", "Column")
                        .WithMany("Tasks")
                        .HasForeignKey("ColumnID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Column");
                });

            modelBuilder.Entity("ApplicationCore.Entities.ScrumBoardAggregate.Board", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("ApplicationCore.Entities.ScrumBoardAggregate.Column", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
